[project] # Update all fields in this section
name = "ClasPar"
dynamic = ["version"]
description = "ClasPar: the friendly classifier parser that parses, filters and writes classifier results to analysis tables."
authors = [{ name = "Jess Friedersdorff", email = "jess.friedersdorff@ukhsa.gov.uk" }]
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "pyyaml",
    "onyx-analysis-helper@git+https://github.com/ukhsa-collaboration/onyx-analysis-helper.git:0.4.0",
    "taxaplease@git+https://github.com/ukhsa-collaboration/gpha-mscape-taxaplease:2.2.0",
    "profiler@https://github.com/ukhsa-collaboration/gpha-mscape-orangebox-profiler/archive/refs/tags/v1.0.0.tar.gz"]

[tool.setuptools.dynamic]
version = { attr = "claspar.__version__" } # Add underscore separated repo name here

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"claspar.data" = ["*.yaml"]

[project.optional-dependencies] # Dependencies for developers only - add more if required
dev = ["ruff", "pytest", "pre-commit"]

[build-system] # Leave this section
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts] # Update with main repo script here
claspar = "claspar.main:main"

[project.urls]
Homepage = "https://github.com/ukhsa-collaboration/gpha-mscape-orangebox-claspar"

[tool.ruff.lint] # Lint rules to follow - add or delete if required
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # comprehesnions
    "C4",
    # pathlib
    "PTH",
]

ignore = ["E501", "UP031"] # Lint rules to ignore - add or remove as required

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
